# Generated by Django 6.0.6 on 2026-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_expiry_alert_sent_booking_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('qr', 'QR Code'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking')], max_length=12),
        ),
    ]
