# Generated by Django 6.0.6 on 2026-08-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_parked_at_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('qr', 'QR Code'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('free', 'Free Parking')], max_length=12),
        ),
    ]
