# Generated by Django 6.0.6 on 2026-08-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Upcoming Booking Reminder'), ('parking_expiry', 'Parking Expiry Reminder'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('slot_update', 'Slot Availability Update'), ('system', 'System Announcement')], default='system', max_length=20),
        ),
    ]
