# Generated by Django 6.0.6 on 2026-07-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('opens_at', models.TimeField(default='00:00:00')),
                ('closes_at', models.TimeField(default='23:59:59')),
                ('is_24_hours', models.BooleanField(default=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=30, max_digits=8)),
                ('price_day_max', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parking_locations/')),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(help_text='Ordering: negative = basement, 0 = ground, positive = upper floors')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='parkinglots.parkinglocation')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('location', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=10)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parkinglots.parkingfloor')),
            ],
            options={
                'ordering': ['row', 'col'],
                'unique_together': {('floor', 'code')},
            },
        ),
    ]
