# Generated by Django 6.0.6 on 2026-08-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='amenities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=100),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='district',
            field=models.CharField(default='Ahmedabad', max_length=100),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='parking_type',
            field=models.CharField(choices=[('municipal', 'Municipal Parking'), ('public', 'Public Parking'), ('private', 'Private Parking'), ('mall', 'Mall Parking'), ('railway_station', 'Railway Station Parking'), ('airport', 'Airport Parking'), ('hospital', 'Hospital Parking'), ('tourist_attraction', 'Tourist Attraction Parking'), ('smart', 'Smart Parking'), ('multi_level', 'Multi-Level Parking')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='state',
            field=models.CharField(default='Gujarat', max_length=100),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='vehicle_types',
            field=models.CharField(default='Car, Bike', max_length=150),
        ),
    ]
