# Generated by Django 6.0.6 on 2026-08-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglots', '0002_parkinglocation_amenities_parkinglocation_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglocation',
            name='parking_type',
            field=models.CharField(choices=[('municipal', 'Municipal Parking'), ('public', 'Public Parking'), ('private', 'Private Parking'), ('mall', 'Mall Parking'), ('railway_station', 'Railway Station Parking'), ('airport', 'Airport Parking'), ('hospital', 'Hospital Parking'), ('tourist_attraction', 'Tourist Attraction Parking'), ('smart', 'Smart Parking'), ('multi_level', 'Multi-Level Parking'), ('bus_station', 'Bus Station Parking')], default='public', max_length=20),
        ),
    ]
