# Generated by Django 6.0.6 on 2026-08-03 17:19

import django.core.validators
import django.db.models.deletion
import parkinglots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('parkinglots', '0003_alter_parkinglocation_parking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='category',
            field=models.CharField(blank=True, choices=[('mall', 'Mall'), ('hospital', 'Hospital'), ('hotel', 'Hotel'), ('office', 'Office'), ('residential', 'Residential'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_locations', to='owners.owner'),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='parking_mode',
            field=models.CharField(choices=[('slot_based', 'Slot-Based Parking'), ('open_ground', 'Open Ground Parking')], default='slot_based', max_length=15),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=12),
        ),
        migrations.CreateModel(
            name='ParkingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parking_gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), parkinglots.models.validate_image_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='parkinglots.parkinglocation')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
