# Generated by Django 6.0.6 on 2026-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglots', '0004_parkinglocation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
