# Generated by Django 6.0.6 on 2026-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglots', '0005_parkinglocation_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='available_days',
            field=models.CharField(default='All Days', max_length=100),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
