# Generated by Django 6.0.6 on 2026-08-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglots', '0006_parkinglocation_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingfloor',
            name='csv_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='csv_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
