# Generated by Django 6.0.6 on 2026-08-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglots', '0007_parkingfloor_csv_ref_parkinglocation_csv_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
