# Generated by Django 6.0.6 on 2026-08-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglots', '0008_parkinglocation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('ev', 'EV'), ('suv', 'SUV'), ('other', 'Other')], default='car', max_length=10),
        ),
    ]
