# Generated by Django 6.0.6 on 2026-08-04 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='owner',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='owner',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='owner',
            name='business_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='owner',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='owner',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='owner_qr_codes/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='OwnerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_received', 'New Booking Received'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('facility_updated', 'Parking Facility Updated'), ('capacity_reached', 'Parking Capacity Reached'), ('limited_availability', 'Limited Parking Availability'), ('csv_upload_success', 'CSV Upload Successful'), ('csv_upload_failed', 'CSV Upload Failed'), ('images_updated', 'Parking Images Updated'), ('details_modified', 'Parking Details Modified'), ('password_changed', 'Password Changed'), ('new_device_login', 'Login from a New Device'), ('system', 'System Announcement'), ('maintenance', 'Maintenance Notification')], max_length=25)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='owners.owner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
